server:
  port: 8601

spring:
  application:
    name: order-service-java
  data:
    mongodb:
      uri: "mongodb+srv://mark:mazare123@greencluster.rewht.mongodb.net/GreenAppDB?retryWrites=true&w=majority"
  rabbitmq:
    host: cow.rmq2.cloudamqp.com
    username: divoayef
    password: GBvJg_Pkw166v1Uu3ri8WZRYXKp1vvZC
    virtual-host: divoayef

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
